import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { Rubik } from "next/font/google";

const rubikFont = Rubik({
	variable: "--font-rubik",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en" suppressHydrationWarning>
			<body
				className={`${rubikFont.variable} antialiased bg-neutral-950`}
			>
				<div className="flex h-screen bg-amber-500/5 text-amber-100">
					<Sidebar />
					<main
						className="w-full m-5 ml-0 rounded-xl
			border border-amber-100/10
			bg-neutral-900/50 backdrop-blur"
					>
						<Navbar />
						<div className="p-5">{children}</div>
					</main>
				</div>
			</body>
		</html>
	);
}
