import type { Metadata } from "next";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import Navbar from "@/components/Navbar";
import { Rubik } from "next/font/google";

const rubikFont = Rubik({
	variable: "--font-rubik",
	subsets: ["latin"],
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${rubikFont.variable} antialiased bg-black`}>
				<div className="flex h-screen bg-amber-300/10 text-primary">
					<Sidebar />
					<main className="border border-amber-100/10 w-full m-5 rounded-lg bg-amber-400/5">
						<Navbar />
						<div className="p-5 ">{children}</div>
					</main>
				</div>
			</body>
		</html>
	);
}
